### ISSUE TITLE
Revise Food Effects

### ISSUE THREAD

**Issue by Cosmic-Whisper** [ColonolNutty/YesChef#6]
For example, eating mountain-man stew grants you a buff that no longer exists in-game; we'll need to compare and contrast and give the closest effect possible.

**Comment by ColonolNutty** [comment]
They may also be missing their foodValue property, this is what feeds the hunger bar.

**Comment by ColonolNutty** [comment]
Looks like maxenergyboost50 doesn't exist, the ones that exist now that could potentially replace it (we could also add more):

- maxenergyboostaugment1
- maxenergyboostaugment2
- maxenergyboostaugment3

**Comment by ColonolNutty** [comment]
or what we could do, according to the lua is have a bit like this
```
"stats": [
   "maxEnergy": 50
]
```
I'm not even sure if that is the right format

**Comment by ColonolNutty** [comment]
Or maybe it would just be `"energyAmount": 50` as a property of its own?

**Comment by ColonolNutty** [comment]
Seems fixed with the latest changes
