### ISSUE TITLE
update crafting recipes

### ISSUE THREAD

**Issue by asperrusual** [ColonolNutty/YesChef#7]
appliances on the kitchen crafting table require a hefty amount of copper and iron and glass blocks instead of glass material. As well, some of the jam recipes require glass blocks too where maybe glass bottles could be substituted in

**Comment by ColonolNutty** [comment]
Hmm, didn't think of using the bottles instead of the glass, that's a good idea

**Comment by ColonolNutty** [comment]
What would be more balanced amounts for the appliances? Those were the amounts the author had originally set them as

**Comment by asperrusual** [comment]
i was thinking maybe 3 or 5 for each. otherwise you're looking at 40-60 copper and iron to complete a whole kitchen set

**Comment by ColonolNutty** [comment]
I'm thinking 10 to 15 for each, so like 5 cop 5 iron, or 6 cop 4 iron

**Comment by ColonolNutty** [comment]
@asperrusual Hey I made a change to the recipes, let me know what you think of them

**Comment by ColonolNutty** [comment]
Haven't heard anything in almost a month so I'll assume it's good
